import React from "react"
import { Popover } from "./Popover"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  "https://www.figma.com/design/8AQj34ysfReEm8l3z7asLu/DevMode-Demo?node-id=1048%3A6844",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      open: figma.enum("State", {
        Open: true,
      }),
      // No matching props could be found for these Figma properties:
      // "slotContent": figma.instance('Slot <Content>'),
      // "style": figma.enum('Style', {
      //   "Default": "default",
      //   "New York": "new-york"
      // })
    },
    example: (props) => <Popover open={props.open} />,
  },
)
