import React from "react"
import { TabsTrigger } from "./Tabs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TabsTrigger,
  "https://www.figma.com/design/8AQj34ysfReEm8l3z7asLu/DevMode-Demo?node-id=128%3A953",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
    },
    example: (props) => (
      <TabsTrigger
        value={props.label}
        disabled={props.disabled}
      >
        {props.label}
      </TabsTrigger>
    ),
  },
)
